language: android
jdk: oraclejdk8

android:
  components:
    - build-tools-23.0.0
    - android-23
    
before_install:
 - chmod +x gradlew

script:
  ./gradlew build
  
sudo: required

after_success:
  - echo "Build was successful. $TRAVIS_TEST_RESULT"
  - ls -l $TRAVIS_BUILD_DIR/target
