language: android
jdk: oraclejdk8

android:
  components:
    - build-tools-23.0.0
    - android-23
    
before_install:
 - chmod +x gradlew

script:
  ./gradlew build
  
sudo: required

deploy:
 provider: azure_web_apps
 username: nikkas
 password: Nkas48695458
 site: grouplock
 skip_cleanup: true
 verbose: true

